name: Allocate release version

on:
  push:
    tags:
      - latest

jobs:
  release:
    permissions:
      contents: write
      id-token: write
    uses: f4ah6o/calver-action/.github/workflows/rust-crate.yaml@ed77f35391c8a334e420974bb7983b0a13fc5deb # 2026.8.0
    with:
      format: YYYY.MM.PATCH
      timezone: Asia/Tokyo
      tag_prefix: v
      source_branch: main
      registry_publish: false
